export default [
  {
    company: 'a',
    employeeCount: 45,
    category: 1,
    product: 'Product A',
    price: 120,
  },
  {
    company: 'a',
    employeeCount: 45,
    category: 1,
    product: 'Product B',
    price: 80,
  },
  {
    company: 'a',
    employeeCount: 45,
    category: 2,
    product: 'Product C',
    price: 105.1,
  },
  {
    company: 'a',
    employeeCount: 45,
    category: 2,
    product: 'Product D',
    price: 95.4,
  },
  {
    company: 'b',
    employeeCount: 30,
    category: 1,
    product: 'Product A',
    price: 40,
  },
  {
    company: 'b',
    employeeCount: 30,
    category: 1,
    product: 'Product B',
    price: 100.99,
  },
  {
    company: 'b',
    employeeCount: 30,
    category: 2,
    product: 'Product C',
    price: 60.23,
  },
  {
    company: 'b',
    employeeCount: 30,
    category: 2,
    product: 'Product D',
    price: 130,
  },
];
